name: Update Rules
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Update Rules
        continue-on-error: true
        run: |
          bash ./data/run.sh
          
